// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace recipe_api.Migrations
{
    [DbContext(typeof(RecipieDb))]
    [Migration("20260228202902_ChangeRelations")]
    partial class ChangeRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("OnlineRecipieId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OnlineRecipieId");

                    b.HasIndex("RecipieId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("OnlineRecipie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OnlineRecipie");
                });

            modelBuilder.Entity("Recipie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CookingTime")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Ingredients")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Instructions")
                        .HasColumnType("longtext");

                    b.Property<string>("PortionSize")
                        .HasColumnType("longtext");

                    b.Property<string>("PreparationTime")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Recipie");
                });

            modelBuilder.Entity("MealPlan", b =>
                {
                    b.HasOne("OnlineRecipie", "OnlineRecipie")
                        .WithMany("MealPlans")
                        .HasForeignKey("OnlineRecipieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Recipie", "Recipie")
                        .WithMany("MealPlans")
                        .HasForeignKey("RecipieId");

                    b.Navigation("OnlineRecipie");

                    b.Navigation("Recipie");
                });

            modelBuilder.Entity("OnlineRecipie", b =>
                {
                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("Recipie", b =>
                {
                    b.Navigation("MealPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
